# -*- coding: utf-8 -*-
"""Calculadora_Projeto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V1KOlawHICo26aIkjaDb859iV8QquBeO
"""

print("\n---------------Minha Calculadora em Python------------------\n")

#Definindo operações com as funções e já retornamos.

def soma(x, y):
  return x + y
def subtracao(x,y):
  return x - y
def divisao(x,y):
  return x / y
def multiplicacao(x,y):
  return x * y

#Aqui imprimos as mensagens ao usuarios na tela 

print("\n Selecione o número da operação desejada: \n")  # Solicitamos os valores ao usuario.
print("1 - Soma")
print("2 - Subtração")
print("3 - Divisão")
print("4 - Multiplicação")


escolha = input("\nDigite sua opção (1/2/3/4): ")

num1 = int(input("\nDigite um número: ")) #usuario digita o valor e a função int já converte o string.
num2 = int(input("\nDigite um número: "))

# Aqui definimos os acontecimentos de acordo com a escolha do usuario.

if escolha == '1':
  print("\n")
  print(num1, "+", num2, "=", soma(num1, num2))
  print("\n")

elif escolha == '2':
  print("\n")
  print(num1, "-", num2, "-", subtracao(num1, num2))
  print("\n")

elif escolha == '3':
  print("\n")
  print(num1, "/", num2, "=", divisao(num1,num2))
  print("\n")

elif escolha == '4':
  print("\n")
  print(num1, "*", num2, "=", multiplicacao(num1,num2)) 

#caso o usuario escolha algo que não esteja definido o código retorna o Print

else:
  print("\nOpção Invalida")